import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import getUsers  from '../lib/pick_button.js'
const { PrismaClient } = require('@prisma/client');



export async function getStaticProps(){
  const prisma = new PrismaClient();
  const users = prisma.user.findMany();
  const jsonusers = JSON.parse(JSON.stringify(users)
  <>
  return {
    props: jsonusers,
    }
  </>
export default function Home({users}) {

  return (
    <section className={styles.maincontainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <div className={styles.header}>
          <div className={styles.item1}>
            <h2>Item 1 </h2>
          </div>

          <div className={styles.item2}>
            <h2>Item 2 </h2>
          </div>

          <div className={styles.login_info}>
            <h2>Login info </h2>
          </div>
        </div>
      </header>
      <body className={styles.body}>
        <div className={styles.body_row_1}>
          {/*<ul className={styles.list}>
          users.map(({id, name, email, pickOrder, custodian, factionId, gameGroupId }) => (
          <li className={styles.listItem} key={id}>
            <a>{name}</a>
          <br />
            <a>{email}</a>
          <br />
            <a>{pickOrder}</a>
          <br />
            <a>{custodian}</a>
          <br />
            <a>{factionId}</a>
          <br />
            <a>{gameGroupId}</a>
        </li>
          ))}
          </ul>*/}

          <div className={styles.galaxy}>
            <h2>galaxy</h2>
          </div>

          <div className={styles.pick_order}>
            <h2>Pick order </h2>
          </div> 
          </div>
        <div className={styles.body_row_2}>
          <div className={styles.picks}>
            <h2>Picks </h2>
          </div>

          <div className={styles.item3}>
            <h2>Item 3 </h2>
          </div>
        </div>

      </body>
      </section>

      )
}